### ISSUE TITLE
Console Output

### ISSUE THREAD

**Issue by Sapython** [lneuhaus/pysine#5]
Traceback (most recent call last):
  File "C:\Users\saptam\AppData\Local\Programs\Python\Python36-32\lib\runpy.py",
 line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\saptam\AppData\Local\Programs\Python\Python36-32\lib\runpy.py",
 line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\saptam\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\pysine\__main__.py", line 21, in <module>
    kwargs['duration'] = float(sys.argv[2])
ValueError: could not convert string to float: 'duration'

**Comment by lneuhaus** [comment]
What do you do to get this error? Which command produces this output?

Am 29.12.2018 14:15 schrieb "Sapython" <notifications@github.com>:

Traceback (most recent call last):
File
"C:\Users\saptam\AppData\Local\Programs\Python\Python36-32\lib\runpy.py",
line 193, in _run_module_as_main
"*main*", mod_spec)
File
"C:\Users\saptam\AppData\Local\Programs\Python\Python36-32\lib\runpy.py",
line 85, in


*run_code exec(code, run_globals) File
"C:\Users\saptam\AppData\Local\Programs\Python\Python36-32\lib\site-packa
ges\pysine_main*.py", line 21, in
kwargs['duration'] = float(sys.argv[2])
ValueError: could not convert string to float: 'duration'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lneuhaus/pysine/issues/5>, or mute the thread

**Comment by lneuhaus** [comment]
```python -m pysine 1000 2,1```
produces above error on my machine. 

If I change it to 
```python -m pysine 1000 2.1```
it works. 

If there is any problem not covered by my answer, please re-open the issue.
